export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const POST_FETCH_START = 'POST_FETCH_START'
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS'
export const POST_FETCH_FAIL = 'POST_FETCH_FAIL'

export const POST_DELETE_START = 'POST_DELETE_START'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL'

export const POST_WRITE_START = 'POST_WRITE_START'
export const POST_WRITE_SUCCESS = 'POST_WRITE_SUCCESS'
export const POST_WRITE_FAIL = 'POST_WRITE_FAIL'


export const FETCH_POST_ITSELF_START = 'FETCH_POST_ITSELF_START'
export const FETCH_POST_ITSELF_SUCCESS = 'FETCH_POST_ITSELF_SUCCESS'
export const FETCH_POST_ITSELF_FAIL = 'FETCH_POST_ITSELF_FAIL'